# fmt: off
from pathlib import Path

MAIN_DIR = Path("/app/workspace")
DATA_DIR = "data"

# Raw
JOURNAL_RAW_FILE_NAME = "Journal_04_09_2024_15_46_57.xlsx"
PLAN_COMPTABLE_RAW_FILE_NAME = "images_92ad70e6f76decd8f7df5903f11304f5-plan-comptable-simplifie-excel.xlsx"
JOURNAL_RAW_FILE_PATH = MAIN_DIR / DATA_DIR / JOURNAL_RAW_FILE_NAME
PLAN_COMPTABLE_RAW_FILE_PATH = MAIN_DIR / DATA_DIR / PLAN_COMPTABLE_RAW_FILE_NAME

# Structured
JOURNAL_STRUCTURED_FILE_NAME = "journal_structured.parquet"
COMPTE_CHARGES_STRUCTURED_FILE_NAME = "comptes_charges_structured.parquet"
JOURNAL_STRUCTURED_FILE_PATH = MAIN_DIR / DATA_DIR / JOURNAL_STRUCTURED_FILE_NAME
COMPTE_CHARGES_STRUCTURED_FILE_PATH = MAIN_DIR / DATA_DIR / COMPTE_CHARGES_STRUCTURED_FILE_NAME

# Enriched
CUBE_FILE_NAME = "cube.parquet"
CUBE_FILE_PATH = MAIN_DIR / DATA_DIR / CUBE_FILE_NAME
